---
abstract: 'A plugin bundle for distributions built by CCM'
author:
  - 'Charles McGarvey <chazmcgarvey@brokenzipper.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test::More: '0'
  blib: '1.01'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.009, CPAN::Meta::Converter version 2.150005'
keywords:
  - dzil
  - author
  - bundle
  - distribution
  - tool
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dist-Zilla-PluginBundle-Author-CCM
no_index:
  directory:
    - eg
    - share
    - shares
    - t
    - xt
provides:
  Dist::Zilla::PluginBundle::Author::CCM:
    file: lib/Dist/Zilla/PluginBundle/Author/CCM.pm
    version: '0.007'
  Pod::Weaver::PluginBundle::Author::CCM:
    file: lib/Pod/Weaver/PluginBundle/Author/CCM.pm
    version: '0.007'
recommends:
  Dist::Zilla::Plugin::FakeRelease: '0'
  Dist::Zilla::Plugin::Prereqs::FromCPANfile: '0'
requires:
  Dist::Zilla: '5.038'
  Dist::Zilla::Plugin::Authority: '0'
  Dist::Zilla::Plugin::AutoPrereqs: '0'
  Dist::Zilla::Plugin::BlockRelease: '0'
  Dist::Zilla::Plugin::CheckChangesHasContent: '0'
  Dist::Zilla::Plugin::ConfirmRelease: '0'
  Dist::Zilla::Plugin::CopyFilesFromBuild: '0'
  Dist::Zilla::Plugin::Encoding: '0'
  Dist::Zilla::Plugin::ExecDir: '0'
  Dist::Zilla::Plugin::Git::Check: '0'
  Dist::Zilla::Plugin::Git::Commit: '0'
  Dist::Zilla::Plugin::Git::CommitBuild: '0'
  Dist::Zilla::Plugin::Git::Contributors: '0'
  Dist::Zilla::Plugin::Git::GatherDir: '0'
  Dist::Zilla::Plugin::Git::NextVersion: '0'
  Dist::Zilla::Plugin::Git::Push: '0'
  Dist::Zilla::Plugin::Git::Tag: '0'
  Dist::Zilla::Plugin::GithubMeta: '0'
  Dist::Zilla::Plugin::Keywords: '0'
  Dist::Zilla::Plugin::License: '0'
  Dist::Zilla::Plugin::MakeMaker: '0'
  Dist::Zilla::Plugin::Manifest: '0'
  Dist::Zilla::Plugin::ManifestSkip: '0'
  Dist::Zilla::Plugin::MetaJSON: '0'
  Dist::Zilla::Plugin::MetaNoIndex: '0'
  Dist::Zilla::Plugin::MetaProvides::Package: '0'
  Dist::Zilla::Plugin::MetaTests: '0'
  Dist::Zilla::Plugin::MetaYAML: '0'
  Dist::Zilla::Plugin::NextRelease: '0'
  Dist::Zilla::Plugin::OverridePkgVersion: '0'
  Dist::Zilla::Plugin::PodCoverageTests: '0'
  Dist::Zilla::Plugin::PodSyntaxTests: '0'
  Dist::Zilla::Plugin::PodWeaver: '0'
  Dist::Zilla::Plugin::Prereqs::AuthorDeps: '0'
  Dist::Zilla::Plugin::PruneCruft: '0'
  Dist::Zilla::Plugin::PruneFiles: '0'
  Dist::Zilla::Plugin::ReadmeAnyFromPod: '0'
  Dist::Zilla::Plugin::ReversionOnRelease: '0'
  Dist::Zilla::Plugin::RunExtraTests: '0'
  Dist::Zilla::Plugin::Test::CPAN::Changes: '0'
  Dist::Zilla::Plugin::Test::CleanNamespaces: '0'
  Dist::Zilla::Plugin::Test::Compile: '0'
  Dist::Zilla::Plugin::Test::EOL: '0'
  Dist::Zilla::Plugin::Test::MinimumVersion: '0'
  Dist::Zilla::Plugin::Test::NoTabs: '0'
  Dist::Zilla::Plugin::Test::Perl::Critic: '0'
  Dist::Zilla::Plugin::Test::Pod::No404s: '0'
  Dist::Zilla::Plugin::Test::Portability: '0'
  Dist::Zilla::Plugin::Test::ReportPrereqs: '0'
  Dist::Zilla::Plugin::TestRelease: '0'
  Dist::Zilla::Plugin::TravisYML: '0'
  Dist::Zilla::Plugin::UploadToCPAN: '0'
  Dist::Zilla::Role::PluginBundle::Config::Slicer: '0'
  Dist::Zilla::Role::PluginBundle::Easy: '0'
  Dist::Zilla::Role::PluginBundle::PluginRemover: '0'
  Dist::Zilla::Util: '0'
  Moose: '0'
  Pod::Elemental::Transformer::List: '0'
  Pod::Elemental::Transformer::Verbatim: '0'
  Pod::Weaver::Config::Assembler: '0'
  Pod::Weaver::Plugin::EnsurePod5: '0'
  Pod::Weaver::Plugin::H1Nester: '0'
  Pod::Weaver::Plugin::SingleEncoding: '0'
  Pod::Weaver::Plugin::Transformer: '0'
  Pod::Weaver::Section::Authors: '0'
  Pod::Weaver::Section::Bugs: '0'
  Pod::Weaver::Section::Collect: '0'
  Pod::Weaver::Section::Contributors: '0'
  Pod::Weaver::Section::Generic: '0'
  Pod::Weaver::Section::Legal: '0'
  Pod::Weaver::Section::Name: '0'
  Pod::Weaver::Section::Region: '0'
  Pod::Weaver::Section::Version: '0'
  Test::CPAN::Meta: '0'
  namespace::autoclean: '0'
  perl: '5.014'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/chazmcgarvey/Dist-Zilla-PluginBundle-Author-CCM/issues
  homepage: https://github.com/chazmcgarvey/Dist-Zilla-PluginBundle-Author-CCM
  repository: https://github.com/chazmcgarvey/Dist-Zilla-PluginBundle-Author-CCM.git
version: '0.007'
x_authority: cpan:CCM
x_serialization_backend: 'YAML::Tiny version 1.70'
